# Generated by Django 4.2 on 2023-04-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
